const $=id=>document.getElementById(id);
const home=$("home"),scannerView=$("scannerView"),loading=$("loading"),result=$("result"),nonWine=$("nonWine"),errorBox=$("error");
let html5QrCode=null,scannerRunning=false,alreadyRead=false;
function hideAll(){[home,scannerView,loading,result,nonWine,errorBox].filter(Boolean).forEach(x=>x.classList.add("hidden"))}
function show(x){hideAll();if(x)x.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function val(v){return v&&String(v).trim()?String(v).trim():"—"}
function code(v){return String(v||"").replace(/\D/g,"")}
function valid(v){return /^[0-9]{8}$|^[0-9]{12}$|^[0-9]{13}$|^[0-9]{14}$/.test(v)}
function tags(w){const t=$("resultTags");if(!t)return;t.innerHTML="";[...new Set([w.type,w.region,w.grape].filter(Boolean))].forEach(x=>{const s=document.createElement("span");s.className="tag";s.textContent=x;t.appendChild(s)})}
function pairings(v){const c=$("pairingChips"),f=$("resultPairings");if(!c||!f)return;c.innerHTML="";const raw=String(v||"").trim(),a=raw.split(/,|;|\n|•/).map(x=>x.trim()).filter(Boolean);if(a.length<2||a.length>8){f.textContent=val(raw);f.classList.remove("hidden");return}f.classList.add("hidden");a.slice(0,6).forEach(x=>{const s=document.createElement("span");s.className="chip";s.textContent=x;c.appendChild(s)})}
async function ask(payload){await stop();show(loading);$("loadingTitle").textContent=payload.mode==="ean"?"Sto verificando il codice "+payload.ean+"…":"Sto analizzando la bottiglia…";$("loadingText").textContent="Prima verifico che il prodotto sia un vino, poi approfondisco le informazioni sul web.";
try{const r=await fetch("/api/sommelier",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Errore del servizio.");const w=d.wine||{};
if(w.non_wine===true||w.is_wine===false){$("nonWineText").textContent=w.message||"Il servizio è dedicato esclusivamente ai vini.";show(nonWine);return}
if(!w.identified){$("errorTitle").textContent="Non riesco a identificarlo con certezza";$("errorText").textContent=w.message||"Prova con una foto più chiara oppure scansiona il codice a barre.";show(errorBox);return}
$("resultName").textContent=val(w.name);$("resultProducer").textContent=val(w.producer);$("resultCode").textContent=w.ean?"EAN / UPC "+w.ean:"";tags(w);$("resultTaste").textContent=val(w.taste);pairings(w.pairings);$("resultTemp").textContent=val(w.temperature);$("resultIdeal").textContent=val(w.ideal_for);$("resultValue").textContent=val(w.value_story);const u=$("uncertain");if(u){if(w.confidence_note){u.textContent=w.confidence_note;u.classList.remove("hidden")}else u.classList.add("hidden")}show(result)}
catch(e){$("errorTitle").textContent="Si è verificato un problema";$("errorText").textContent=e.message||"Riprova tra qualche secondo.";show(errorBox)}}
async function start(){alreadyRead=false;show(scannerView);if(typeof Html5Qrcode==="undefined"){show(errorBox);return}html5QrCode=new Html5Qrcode("reader",{formatsToSupport:[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E,Html5QrcodeSupportedFormats.CODE_128],verbose:false});
try{await html5QrCode.start({facingMode:"environment"},{fps:12,qrbox:(w,h)=>({width:Math.floor(w*.88),height:Math.floor(Math.min(150,h*.3))}),aspectRatio:1.777778},async txt=>{if(alreadyRead)return;const c=code(txt);if(!valid(c))return;alreadyRead=true;if(navigator.vibrate)navigator.vibrate(80);await ask({mode:"ean",ean:c})},()=>{});scannerRunning=true}catch(e){scannerRunning=false;$("errorTitle").textContent="Non riesco ad aprire la fotocamera";$("errorText").textContent="Consenti l'accesso alla fotocamera nel browser e riprova.";show(errorBox)}}
async function stop(){if(html5QrCode&&scannerRunning){try{await html5QrCode.stop()}catch{}scannerRunning=false}if(html5QrCode){try{html5QrCode.clear()}catch{}html5QrCode=null}}
$("scanButton")?.addEventListener("click",start);$("closeScanner")?.addEventListener("click",async()=>{await stop();show(home)});
$("photoButton")?.addEventListener("click",()=>$("photoInput").click());$("photoInput")?.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){$("errorTitle").textContent="Foto troppo grande";$("errorText").textContent="Usa una foto inferiore a 8 MB.";show(errorBox);return}const r=new FileReader();r.onload=()=>ask({mode:"image",image:r.result});r.readAsDataURL(f)});
$("eanForm")?.addEventListener("submit",e=>{e.preventDefault();const c=code($("eanInput")?.value);if(!valid(c)){show(errorBox);return}ask({mode:"ean",ean:c})});
$("backButton")?.addEventListener("click",()=>show(home));$("retryButton")?.addEventListener("click",()=>show(home));$("nonWineRetry")?.addEventListener("click",()=>show(home));
document.addEventListener("visibilitychange",async()=>{if(document.hidden&&scannerRunning)await stop()});
