export default async function handler(req,res){
if(req.method!=="POST")return res.status(405).json({error:"Metodo non consentito"});
const key=process.env.GROQ_API_KEY;if(!key)return res.status(500).json({error:"GROQ_API_KEY non configurata."});
const b=req.body||{},mode=b.mode;if(!["ean","image"].includes(mode))return res.status(400).json({error:"Richiesta non valida."});
async function chat(p){const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Errore Groq.");return d?.choices?.[0]?.message?.content||""}
async function json(p){const x=(await chat(p)).replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/\s*```$/i,"").trim();return JSON.parse(x)}
try{
let ean="",query="",visual="";
if(mode==="image"){
const image=String(b.image||"");if(!/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(image))return res.status(400).json({error:"Formato immagine non supportato."});
const g=await json({model:"qwen/qwen3.6-27b",messages:[{role:"user",content:[{type:"text",text:`Analizza con prudenza la foto. Prima stabilisci se è DAVVERO un vino. Vino=true solo per vino rosso, bianco, rosato, spumante, frizzante, Champagne, Prosecco. NON vino: birra, sidro, distillati, whisky, rum, vodka, gin, grappa, amari, liquori, vermouth, cocktail, acqua, bibite, succhi, olio, aceto, alimenti o altri prodotti. Se non sei sicuro, category_clear=false. Leggi nome, produttore, denominazione, regione, annata, vitigno. Rispondi SOLO JSON: {"category_clear":true,"is_wine":true,"category":"vino rosato","product_name":"nome","producer":"produttore","visible_details":"dettagli"} oppure is_wine false.`},{type:"image_url",image_url:{url:image}}]}],response_format:{type:"json_object"},temperature:0,max_completion_tokens:600});
if(g.category_clear===true&&g.is_wine===false)return res.status(200).json({wine:{identified:false,is_wine:false,non_wine:true,message:"Il prodotto inquadrato non risulta essere un vino. Il Sommelier Virtuale è dedicato esclusivamente ai vini."}});
if(g.category_clear!==true||g.is_wine!==true)return res.status(200).json({wine:{identified:false,message:"Non riesco a verificare con sufficiente certezza che il prodotto sia un vino. Prova a fotografare meglio la bottiglia o l'etichetta."}});
query=[g.product_name,g.producer,g.category,g.visible_details].filter(Boolean).join(" | ");visual=JSON.stringify(g)
}
if(mode==="ean"){ean=String(b.ean||"").replace(/\D/g,"");if(!/^[0-9]{8}$|^[0-9]{12}$|^[0-9]{13}$|^[0-9]{14}$/.test(ean))return res.status(400).json({error:"Codice EAN/UPC non valido."});query=`EAN/UPC ${ean}`}
const research=await chat({model:"groq/compound-mini",messages:[{role:"user",content:mode==="ean"?`Cerca sul web in modo approfondito l'EAN/UPC "${ean}". PRIMA identifica categoria e nome prodotto. Non presumere che sia vino. Se è birra, liquore, distillato, olio, acqua, bibita o altro, dichiaralo chiaramente. Se è vino, raccogli nome, produttore, regione, denominazione, tipologia, vitigno, profilo, abbinamenti, temperatura, occasioni e gli elementi VERIFICABILI che contribuiscono al posizionamento (territorio, denominazione, metodo produttivo, affinamento, reputazione). Puoi usare il prezzo solo come contesto interno, senza giudizi. Non inventare.`:`Dalla foto è emerso un possibile vino: ${query}. Verifica sul web sia che sia davvero vino sia la sua identità. Dettagli visivi: ${visual}. Se confermato, raccogli nome, produttore, regione, denominazione, tipologia, vitigno, profilo, abbinamenti, temperatura, occasioni e gli elementi VERIFICABILI che contribuiscono al posizionamento. Non inventare.`}]});
const guard=await json({model:"openai/gpt-oss-20b",messages:[{role:"user",content:`Filtro di sicurezza per app esclusivamente vini. Dati: ${research}. Rispondi SOLO JSON {"found":true,"is_wine":true,"category":"vino rosato","product_name":"nome","reason":"motivo"}. is_wine=false per birra, sidro, distillati, liquori, vermouth, olio, acqua, bibite e ogni non-vino. Se non identificato con certezza found=false.`}],response_format:{type:"json_object"},temperature:0,max_completion_tokens:400});
if(guard.found===true&&guard.is_wine===false)return res.status(200).json({wine:{identified:false,is_wine:false,non_wine:true,message:"Il prodotto identificato non è un vino. Il Sommelier Virtuale è dedicato esclusivamente ai vini."}});
if(guard.found!==true||guard.is_wine!==true)return res.status(200).json({wine:{identified:false,message:"Non riesco a identificare con sufficiente certezza un vino associato a questa scansione. Prova con una foto più chiara o con il codice a barre della bottiglia."}});
const wine=await json({model:"openai/gpt-oss-20b",messages:[{role:"user",content:`Sei Il Sommelier Virtuale. Prodotto verificato come vino: ${guard.product_name}. Ricerca: ${research}. Crea scheda professionale. Non inventare. pairings=3-6 abbinamenti separati da virgola. value_story=2-3 frasi che spiegano solo elementi verificati che contribuiscono al posizionamento; mai dire costa tanto/poco, economico, scarso, costoso, sovrapprezzato. Vini accessibili: puoi valorizzare immediatezza, freschezza, versatilità SOLO se coerente. Fascia superiore: territorio, denominazione, selezione, metodo, affinamento, reputazione SOLO se verificati. Rispondi SOLO JSON {"identified":true,"is_wine":true,"non_wine":false,"ean":"${ean}","name":"Nome","producer":"Produttore","region":"Regione","type":"Tipologia","grape":"Vitigno","taste":"Profilo","pairings":"A, B, C","temperature":"Temperatura","ideal_for":"Occasioni","value_story":"Valore","confidence_note":""}`}],response_format:{type:"json_object"},temperature:.1,max_completion_tokens:1500});
wine.is_wine=true;wine.non_wine=false;if(mode==="ean")wine.ean=ean;return res.status(200).json({wine});
}catch(e){console.error(e);return res.status(500).json({error:e?.message||"Errore durante la ricerca."})}}
